// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Banco
    {
        [Key]
        public int IdBanco { get; set; }
        public string? NomeBanco { get; set; }
        public int? IdConta { get; set; }

        [ForeignKey("IdConta")]
        [InverseProperty("Banco")]
        public virtual ContaContabeis IdContaNavigation { get; set; }
    }
}