// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Clientes
    {
        public Clientes()
        {
            Projetos = new HashSet<Projetos>();
        }

        [Key]
        public int ClienteId { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("CNPJ")]
        public int? Cnpj { get; set; }
        public int? PaisId { get; set; }

        [ForeignKey("PaisId")]
        [InverseProperty("Clientes")]
        public virtual Pais Pais { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<Projetos> Projetos { get; set; }
    }
}