// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    [Table("ContaContabeis")]
    public partial class ContaContabeis1
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idContaConta")]
        public int? IdContaConta { get; set; }
    }
}