// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    [Table("Conta_Contabeis")]
    public partial class ContaContabeis
    {
        public ContaContabeis()
        {
            Banco = new HashSet<Banco>();
        }

        [Key]
        public int IdConta { get; set; }

        [InverseProperty("IdContaNavigation")]
        public virtual ICollection<Banco> Banco { get; set; }
    }
}