// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Empresa
    {
        public Empresa()
        {
            Funcionarios = new HashSet<Funcionarios>();
        }

        [Key]
        public int IdEmpresa { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Nome { get; set; }

        [InverseProperty("IdEmpresaNavigation")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}