// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Funcionarios
    {
        [Key]
        public int IdFuncionarios { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Nome { get; set; }
        public int? IdEmpresa { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("Funcionarios")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
    }
}