// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Moeda
    {
        public Moeda()
        {
            Pais = new HashSet<Pais>();
        }

        [Key]
        public int MoedaId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Nome { get; set; }
        public double Cotacao { get; set; }

        [InverseProperty("Moeda")]
        public virtual ICollection<Pais> Pais { get; set; }
    }
}