// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Pais
    {
        public Pais()
        {
            Clientes = new HashSet<Clientes>();
        }

        [Key]
        public int PaisId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Nome { get; set; }
        public int? MoedaId { get; set; }

        [ForeignKey("MoedaId")]
        [InverseProperty("Pais")]
        public virtual Moeda Moeda { get; set; }
        [InverseProperty("Pais")]
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}