// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAPI
{
    public partial class Projetos
    {
        [Key]
        public int ProjetosId { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Tamanho { get; set; }
        public int? NumeroPessoas { get; set; }
        public double? Valor { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Prazo { get; set; }
        public int? ClienteId { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("Projetos")]
        public virtual Clientes Cliente { get; set; }
    }
}